version: "3"
services:
  selenium-hub:
    image: selenium/hub:latest
    ports:
      - "4444:4444"
    networks:
      - selenium_grid

  chrome:
    image: selenium/node-chrome:latest
    environment:
      HUB_HOST: selenium-hub
    depends_on:
      - selenium-hub
    networks:
      - selenium_grid

networks:
  selenium_grid:
    external: true
